# Generated by Django 4.2.11 on 2025-02-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('imagen', models.ImageField(upload_to='denuncias_images/')),
                ('categoria', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_creacion', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
