# Generated by Django 4.2.11 on 2025-02-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denuncia',
            old_name='description',
            new_name='descripcion',
        ),
    ]
