# Generated by Django 4.2.11 on 2025-02-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_rename_description_denuncia_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
